Update Splitbutton.html
l0rdn1kk0n/wicket-bootstrap pull request #804
Opened 2019-05-19 14:09 UTC by helmut8080

Adapted for Bootstrap 4: https://getbootstrap.com/docs/4.3/components/dropdowns/#split-button

2019-05-19 15:44 UTC, helmut8080 commented
Only the commit from May 19, 2019 should be merged. Sorry still have difficulties with Github

2019-05-19 19:52 UTC, martin-g requested changes

2019-05-19 19:52 UTC, martin-g commented on bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/button/dropdown/SplitButton.html
> +            <button type="button" wicket:id="button"></button>
why did you remove `class="btn"` ?

2019-05-19 19:52 UTC, martin-g commented on bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/button/dropdown/SplitButton.html
> +                <span class="sr-only">Toggle Dropdown</span>
`Toggle Dropdown` should be i18n-ed.

2019-05-19 19:53 UTC, martin-g commented
> Only the commit from May 19, 2019 should be merged. Sorry still have difficulties with Githu

You need to pull the latest version of this branch and push the merge commit. This should remove the extra commits.

2019-05-27 06:30 UTC, merged

2019-05-27 06:30 UTC, martin-g commented
Thank you, @helmut8080 !