remove sizing of form groups as it is not supported by Bootstrap 4
l0rdn1kk0n/wicket-bootstrap pull request #881
Opened 2020-11-07 23:43 UTC by pinhead84

Hey guys,

Bootstrap 4 does not support sizing of Form Groups. The classes `form-group-sm` & `form-group-lg` are no more available in their CSS and its not available in their documentation anymore. Therefore this PR removes the corresponding code from the `FormGroup` class.

It might lead to compilation problems, if developers are still using `FormGroup.Size` in their application. Do you prefer using deprecation annotations instead of just removing this feature?

2020-11-08 09:04 UTC, martin-g requested changes
Hi @pinhead84 !

Thanks for the PR!
We cannot remove the public APIs in minor release. Let's do it with deprecation!

2020-11-08 09:04 UTC, martin-g commented on bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/form/FormGroup.java
> -    public enum Size implements ICssClassNameProvider {
Let's just deprecate the enum. It will be removed later, probably in a major version.

2020-11-08 09:04 UTC, martin-g commented on bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/form/FormGroup.java
> -    public FormGroup size(final Size size) {
deprecate

2020-11-08 09:04 UTC, martin-g commented on bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/form/FormGroup.java
> -        if (size != null) {
Let's write a warning log here that size is ignored.

2020-11-08 09:04 UTC, martin-g commented on bootstrap-core/src/test/java/de/agilecoders/wicket/core/markup/html/bootstrap/form/FormGroupTest.java
> -    @Test
This is OK to be removed!

2020-11-08 17:45 UTC, pinhead84 commented
Hey Martin,

thanks for the quick response and your notes. 

- I've restored the public API and marked it as deprecated with a plausible message.
- All private stuff regarding resizing is already removed.
- A warning is logged, if the public `FormGroup.size()` method is called.

Or do you prefer keeping the private API intact? - Maybe a developer still uses the `form-group-lg` / `form-group-sm` classes in his CSS definitions. Currently they are not written anymore, which may lead to rendering issues. In this case we might still keep the tests, even if the feature is deprecated.

Best regards.

2020-11-09 06:22 UTC, martin-g approved these changes

2020-11-09 06:23 UTC, merged

2020-11-09 06:23 UTC, martin-g commented
Thank you, @pinhead84 !